safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Kuiper
host: localhost
email: oyyj42@126.com

#desc: "All in, Saturation attack. "
description: "All in, Saturation attack. "
markdown: kramdown
#baseurl: /blog
        
custom:
    category:
        java: 一点Java 
        android: Android 拆轮子与造轮子i
        thinking: 思鉴录
        efficency: 银弹和效率
        python: Python

    categories:
      - name:  java
        title: 一点Java

      - name:  android
        title: Android 拆轮子与造轮子

      - name: thinking
        title: 思鉴录

      - name: efficency
        title: 银弹和效率 

      - name: python
        title: Python

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Kuiper
        email: oyyj42@126.com
        disqus: 我             # Disqus缩略标识
        #gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: https://github.com/oyyj42                 # GitHub账号
        gravatar: 4daa45ae0ee7d40d600dcc6d0ea601a5  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
